### ISSUE TITLE
现在的学生邮箱好像不能申请Jetbrains教育授权了

### ISSUE THREAD

**Issue by uselessbug** [TowerPro/ZJGSU-guidance#1]
![图片](https://user-images.githubusercontent.com/61285640/131945034-80f321fd-71c9-4141-a33e-278e5bfbc7c6.png)
泪目

**Comment by TowerPro** [comment]
泪目。。。问一下学校网管

**Comment by TowerPro** [comment]
> ![图片](https://user-images.githubusercontent.com/61285640/131945034-80f321fd-71c9-4141-a33e-278e5bfbc7c6.png) 泪目

hello，我用研究生的邮箱申请了一下（走学信网/github education）是可以认证的，不过现在不能无限续费了
![2021-11-03 14 13 44](https://user-images.githubusercontent.com/35908547/140016478-ba68246e-20cb-4d93-8466-384614e304a0.jpg)

**Comment by uselessbug** [comment]
> 
> 
> > ![图片](https://user-images.githubusercontent.com/61285640/131945034-80f321fd-71c9-4141-a33e-278e5bfbc7c6.png) 泪目
> 
> hello，我用研究生的邮箱申请了一下（走学信网/github education）是可以认证的，不过现在不能无限续费了 ![2021-11-03 14 13 44](https://user-images.githubusercontent.com/35908547/140016478-ba68246e-20cb-4d93-8466-384614e304a0.jpg)

原来如此，感谢回复——
我是本科新生，学信网目前也没录入学籍（学校为了让本科一年级不在第一学期报考CET4的手段），所以没能申请成功...
另外github edu也不能直接申请，需要上传资料，请问你申请的时候需要这样吗（？）（我上传了两次资料，都被reject了（哭）

**Comment by TowerPro** [comment]
> > > ![图片](https://user-images.githubusercontent.com/61285640/131945034-80f321fd-71c9-4141-a33e-278e5bfbc7c6.png) 泪目
> > 
> > 
> > hello，我用研究生的邮箱申请了一下（走学信网/github education）是可以认证的，不过现在不能无限续费了 ![2021-11-03 14 13 44](https://user-images.githubusercontent.com/35908547/140016478-ba68246e-20cb-4d93-8466-384614e304a0.jpg)
> 
> 原来如此，感谢回复—— 我是本科新生，学信网目前也没录入学籍（学校为了让本科一年级不在第一学期报考CET4的手段），所以没能申请成功... 另外github edu也不能直接申请，需要上传资料，请问你申请的时候需要这样吗（？）（我上传了两次资料，都被reject了（哭）

工商的邮箱github应该无法认证成功，我之前尝试的时候也是失败的，研究生的还没有试过
